using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using operations.Application.Common.Interfaces;
using operations.Application.Common.Storage;

namespace operations.Infrastructure.Storage;

/// <summary>
/// File-system-backed <see cref="IFileStorageProvider"/> for Development.
///
/// Files are written under <see cref="LocalStorageOptions.RootPath"/> using the
/// <see cref="FileStorageKeyGenerator"/> key as a relative sub-path. The key is
/// always server-generated, so directory traversal (keys containing <c>..</c>) is
/// impossible by construction — but a defence-in-depth check is applied in
/// <see cref="ResolvePath"/> anyway.
///
/// <para>This provider does NOT serve public URLs. Use the streaming endpoint
/// (<c>GET /api/v1/admin/garment-inspections/photos/{photoId}</c>) to read files back through the API.</para>
///
/// <para>Activated when <c>Storage:Provider = local</c> (the default in Development).</para>
/// </summary>
internal sealed class LocalFileStorageProvider : IFileStorageProvider
{
    private readonly string _root;
    private readonly ILogger<LocalFileStorageProvider> _logger;

    public LocalFileStorageProvider(
        IOptions<LocalStorageOptions> options,
        ILogger<LocalFileStorageProvider> logger)
    {
        _logger = logger;
        var root = options.Value.RootPath;
        if (string.IsNullOrWhiteSpace(root))
            throw new InvalidOperationException(
                "Storage:Local:RootPath is required when Storage:Provider = 'local'. " +
                "Set it in appsettings.Development.json or via an env var.");

        _root = Path.GetFullPath(root);
        _logger.LogInformation("[LocalFileStorage] Root: {Root}", _root);
    }

    /// <inheritdoc/>
    public async Task<string> SaveAsync(
        Stream content, string contentType, string keyHint, Guid brandId,
        CancellationToken ct = default)
    {
        var key      = FileStorageKeyGenerator.Generate(brandId, keyHint, contentType);
        var filePath = ResolvePath(key);

        Directory.CreateDirectory(Path.GetDirectoryName(filePath)!);

        await using var fs = new FileStream(filePath, FileMode.Create, FileAccess.Write, FileShare.None,
            bufferSize: 81920, useAsync: true);
        await content.CopyToAsync(fs, ct);

        _logger.LogDebug("[LocalFileStorage] Saved {Key} ({ContentType})", key, contentType);
        return key;
    }

    /// <inheritdoc/>
    public Task<Stream> OpenReadAsync(string key, CancellationToken ct = default)
    {
        var filePath = ResolvePath(key);
        if (!File.Exists(filePath))
            throw new FileNotFoundException($"Storage object not found: {key}", filePath);

        Stream stream = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.Read,
            bufferSize: 81920, useAsync: true);
        return Task.FromResult(stream);
    }

    /// <inheritdoc/>
    public Task DeleteAsync(string key, CancellationToken ct = default)
    {
        var filePath = ResolvePath(key);
        if (File.Exists(filePath))
        {
            File.Delete(filePath);
            _logger.LogDebug("[LocalFileStorage] Deleted {Key}", key);
        }
        return Task.CompletedTask;
    }

    /// <inheritdoc/>
    public string? GetPublicUrl(string key) => null; // local storage is never publicly addressable

    // ── Path safety ───────────────────────────────────────────────────────────

    private string ResolvePath(string key)
    {
        // Keys are always generated by FileStorageKeyGenerator, so they cannot
        // contain ".." segments — but we validate anyway as a defence-in-depth measure.
        ArgumentException.ThrowIfNullOrWhiteSpace(key);

        var fullPath = Path.GetFullPath(Path.Combine(_root, key));

        if (!fullPath.StartsWith(_root, StringComparison.OrdinalIgnoreCase))
            throw new InvalidOperationException(
                $"Storage key '{key}' resolves outside the storage root — potential path traversal attempt.");

        return fullPath;
    }
}
