/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppRateCardsRouteImport } from './routes/_app/rate-cards'
import { Route as AppQualityRouteImport } from './routes/_app/quality'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppConsentRouteImport } from './routes/_app/consent'
import { Route as AppCampaignsRouteImport } from './routes/_app/campaigns'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppTemplatesIndexRouteImport } from './routes/_app/templates.index'
import { Route as AppCampaignsIndexRouteImport } from './routes/_app/campaigns.index'
import { Route as AppTemplatesNewRouteImport } from './routes/_app/templates.new'
import { Route as AppTemplatesTemplateIdRouteImport } from './routes/_app/templates.$templateId'
import { Route as AppCampaignsNewRouteImport } from './routes/_app/campaigns.new'
import { Route as AppCampaignsCampaignIdRouteImport } from './routes/_app/campaigns.$campaignId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppRateCardsRoute = AppRateCardsRouteImport.update({
  id: '/rate-cards',
  path: '/rate-cards',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityRoute = AppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppConsentRoute = AppConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTemplatesRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const AppTemplatesNewRoute = AppTemplatesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTemplatesRoute,
} as any)
const AppTemplatesTemplateIdRoute = AppTemplatesTemplateIdRouteImport.update({
  id: '/$templateId',
  path: '/$templateId',
  getParentRoute: () => AppTemplatesRoute,
} as any)
const AppCampaignsNewRoute = AppCampaignsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const AppCampaignsCampaignIdRoute = AppCampaignsCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => AppCampaignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/billing': typeof AppBillingRoute
  '/campaigns': typeof AppCampaignsRouteWithChildren
  '/consent': typeof AppConsentRoute
  '/messages': typeof AppMessagesRoute
  '/quality': typeof AppQualityRoute
  '/rate-cards': typeof AppRateCardsRoute
  '/templates': typeof AppTemplatesRouteWithChildren
  '/campaigns/$campaignId': typeof AppCampaignsCampaignIdRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/templates/new': typeof AppTemplatesNewRoute
  '/campaigns/': typeof AppCampaignsIndexRoute
  '/templates/': typeof AppTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/billing': typeof AppBillingRoute
  '/consent': typeof AppConsentRoute
  '/messages': typeof AppMessagesRoute
  '/quality': typeof AppQualityRoute
  '/rate-cards': typeof AppRateCardsRoute
  '/': typeof AppIndexRoute
  '/campaigns/$campaignId': typeof AppCampaignsCampaignIdRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/templates/new': typeof AppTemplatesNewRoute
  '/campaigns': typeof AppCampaignsIndexRoute
  '/templates': typeof AppTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/campaigns': typeof AppCampaignsRouteWithChildren
  '/_app/consent': typeof AppConsentRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/quality': typeof AppQualityRoute
  '/_app/rate-cards': typeof AppRateCardsRoute
  '/_app/templates': typeof AppTemplatesRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/campaigns/$campaignId': typeof AppCampaignsCampaignIdRoute
  '/_app/campaigns/new': typeof AppCampaignsNewRoute
  '/_app/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/_app/templates/new': typeof AppTemplatesNewRoute
  '/_app/campaigns/': typeof AppCampaignsIndexRoute
  '/_app/templates/': typeof AppTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/billing'
    | '/campaigns'
    | '/consent'
    | '/messages'
    | '/quality'
    | '/rate-cards'
    | '/templates'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/templates/$templateId'
    | '/templates/new'
    | '/campaigns/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/billing'
    | '/consent'
    | '/messages'
    | '/quality'
    | '/rate-cards'
    | '/'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/templates/$templateId'
    | '/templates/new'
    | '/campaigns'
    | '/templates'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/billing'
    | '/_app/campaigns'
    | '/_app/consent'
    | '/_app/messages'
    | '/_app/quality'
    | '/_app/rate-cards'
    | '/_app/templates'
    | '/_app/'
    | '/_app/campaigns/$campaignId'
    | '/_app/campaigns/new'
    | '/_app/templates/$templateId'
    | '/_app/templates/new'
    | '/_app/campaigns/'
    | '/_app/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rate-cards': {
      id: '/_app/rate-cards'
      path: '/rate-cards'
      fullPath: '/rate-cards'
      preLoaderRoute: typeof AppRateCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality': {
      id: '/_app/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AppQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consent': {
      id: '/_app/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof AppConsentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/': {
      id: '/_app/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppTemplatesRoute
    }
    '/_app/campaigns/': {
      id: '/_app/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/_app/templates/new': {
      id: '/_app/templates/new'
      path: '/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof AppTemplatesNewRouteImport
      parentRoute: typeof AppTemplatesRoute
    }
    '/_app/templates/$templateId': {
      id: '/_app/templates/$templateId'
      path: '/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof AppTemplatesTemplateIdRouteImport
      parentRoute: typeof AppTemplatesRoute
    }
    '/_app/campaigns/new': {
      id: '/_app/campaigns/new'
      path: '/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AppCampaignsNewRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/_app/campaigns/$campaignId': {
      id: '/_app/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof AppCampaignsCampaignIdRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
  }
}

interface AppCampaignsRouteChildren {
  AppCampaignsCampaignIdRoute: typeof AppCampaignsCampaignIdRoute
  AppCampaignsNewRoute: typeof AppCampaignsNewRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
}

const AppCampaignsRouteChildren: AppCampaignsRouteChildren = {
  AppCampaignsCampaignIdRoute: AppCampaignsCampaignIdRoute,
  AppCampaignsNewRoute: AppCampaignsNewRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
}

const AppCampaignsRouteWithChildren = AppCampaignsRoute._addFileChildren(
  AppCampaignsRouteChildren,
)

interface AppTemplatesRouteChildren {
  AppTemplatesTemplateIdRoute: typeof AppTemplatesTemplateIdRoute
  AppTemplatesNewRoute: typeof AppTemplatesNewRoute
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
}

const AppTemplatesRouteChildren: AppTemplatesRouteChildren = {
  AppTemplatesTemplateIdRoute: AppTemplatesTemplateIdRoute,
  AppTemplatesNewRoute: AppTemplatesNewRoute,
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
}

const AppTemplatesRouteWithChildren = AppTemplatesRoute._addFileChildren(
  AppTemplatesRouteChildren,
)

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppCampaignsRoute: typeof AppCampaignsRouteWithChildren
  AppConsentRoute: typeof AppConsentRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppQualityRoute: typeof AppQualityRoute
  AppRateCardsRoute: typeof AppRateCardsRoute
  AppTemplatesRoute: typeof AppTemplatesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppCampaignsRoute: AppCampaignsRouteWithChildren,
  AppConsentRoute: AppConsentRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppQualityRoute: AppQualityRoute,
  AppRateCardsRoute: AppRateCardsRoute,
  AppTemplatesRoute: AppTemplatesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
