namespace operations.Application.Common.Interfaces;

/// <summary>
/// Abstraction for binary file storage (photos, signatures, documents).
///
/// <para><b>Key scheme</b> — all implementations use the same server-generated key format:</para>
/// <code>
///   {brandId:N}/{area}/{uuid:N}.{ext}
///   e.g.  a1b2c3d4e5f6.../inspections/7f8a9b0c....jpg
/// </code>
/// Keys are generated by <see cref="FileStorageKeyGenerator"/> and are NEVER
/// supplied by callers — this prevents path-traversal and filename-injection attacks.
///
/// <para>Migrated from the legacy <c>wavio.ServiceDefaults.Storage</c>. The interface lives in
/// operations.Application; the concrete <c>LocalFileStorageProvider</c> lives in operations.Infrastructure
/// and is registered via <c>AddOperationsInfrastructure</c>.</para>
/// </summary>
public interface IFileStorageProvider
{
    /// <summary>
    /// Persists <paramref name="content"/> and returns the opaque storage key.
    /// The key is durable and suitable for storing in the database.
    /// </summary>
    /// <param name="content">Seekable readable stream. The provider does NOT dispose it.</param>
    /// <param name="contentType">MIME type (e.g. <c>image/jpeg</c>).</param>
    /// <param name="keyHint">Describes the purpose / sub-area (e.g. <c>inspections</c>, <c>proof</c>).
    /// Used as an intermediate path segment; must match <c>[a-z0-9_/-]</c>.</param>
    /// <param name="brandId">Tenant brand GUID — forms the first path segment for tenant isolation.</param>
    /// <returns>Opaque storage key. Pass to <see cref="OpenReadAsync"/> or <see cref="DeleteAsync"/>.</returns>
    Task<string> SaveAsync(Stream content, string contentType, string keyHint, Guid brandId, CancellationToken ct = default);

    /// <summary>
    /// Opens a read stream for the object identified by <paramref name="key"/>.
    /// Throws <see cref="FileNotFoundException"/> (local) or equivalent if the object does not exist.
    /// </summary>
    Task<Stream> OpenReadAsync(string key, CancellationToken ct = default);

    /// <summary>
    /// Removes the object identified by <paramref name="key"/>. No-ops if the object does not exist.
    /// </summary>
    Task DeleteAsync(string key, CancellationToken ct = default);

    /// <summary>
    /// Returns a public URL for the object, or <c>null</c> when the provider does not expose
    /// objects publicly (e.g. the local provider in Development).
    /// </summary>
    string? GetPublicUrl(string key);
}
